# -*- mode: ruby -*-

# Sometimes the boot stalls. This is due to cloud-init forcing the network to come up. This has a time out of ~ 2-3 minutes. Just wait...

NAME = File.basename(File.dirname(__FILE__)).gsub('_', '-').gsub(/[^\w]/, '')

DEVTOOLS = <<SCRIPT
apt-get -y install vim man wget
SCRIPT

RUBY_PKG = <<SCRIPT
apt-get install software-properties-common
apt-add-repository -y ppa:brightbox/ruby-ng
apt-get update
apt-get install -y ruby2.2 ruby-switch
ruby-switch --set ruby2.2
gem install bundler
SCRIPT

# RUBY_RVM = <<SCRIPT
# curl -sSL https://rvm.io/mpapis.asc | gpg --import -
# curl -sSL https://get.rvm.io | bash -s stable
# source ~/.rvm/scripts/rvm
# rvm install ruby-2.2.1
# gem install bundler
# SCRIPT

BUNDLES = <<SCRIPT
pushd /vagrant
bundle install
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  # config.vm.box = "ubuntu/trusty64"
  # config.vm.box = "ubuntu/vivid64"
  config.vm.hostname = NAME

  config.vm.provision :shell, inline: DEVTOOLS, keep_color: true
  config.vm.provision :shell, inline: RUBY_PKG, keep_color: true
  # config.vm.provision :shell, inline: RUBY_RVM, keep_color: true, privileged: false
  config.vm.provision :shell, inline: BUNDLES, keep_color: true, privileged: false

  config.vm.network "forwarded_port", guest: 4000, host: 4000

  config.vm.provider "virtualbox" do |vb|
    vb.name = NAME
    vb.memory = 1024
    vb.gui = false
  end
end
